#version: '3.8'
#services:
#  pro-management:
#    image: mysql:latest
#    environment:
#      - MYSQL_ROOT_PASSWORD=1234$$
#      - MYSQL_DATABASE=pro-management
#      - MYSQL_USER=testuser
#      - MYSQL_PASSWORD=testuser@123
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./obo.sql:/docker-entrypoint-initdb.d/init.sql
#
#  web:
#    image: obo-spring:latest
#    ports:
#      - 8888:8888
#    depends_on:
#      - pro-management
#
#volumes:
#  mysql-data:

#  springboot-docker-container:
#    image: springboot-docker-container
#    ports:
#      - 8888:8888
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - pro-management

#services:
#  mysql-standalone1:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=admin123
#      - MYSQL_DATABASE=test
#      - MYSQL_USER=testuser
#      - MYSQL_PASSWORD=testuser@123
#  springboot-docker-container:
#    image: springboot-docker-container
#    ports:
#      - 8082:8080
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql-standalone1

version: '3.7'

services:
  pro-management:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234$$
      - MYSQL_DATABASE=pro-management
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser@123
    ports:
      - 3307:3306
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - 8888:8888
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pro-management:3306/pro-management?autoReconnect=true&useSSL=false
    depends_on:
      - pro-management
